global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'alert.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'loki'
    dns_sd_configs:
      - names:
          - loki
        type: A
        port: 3100
  - job_name: 'promtail'
    dns_sd_configs:
      - names:
          - promtail
        type: A
        port: 9080
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'
  # - job_name: mysql
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   static_configs:
  #     - targets:
  #       - 192.168.3.188:3306
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: 192.168.3.188:9104
